name: Run Python script every 10 minutes

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the Python script
        run: python backend/story1.py

      - name: Configure Git
        run: |
          git config user.name "RiptideVideos"
          git config user.email "riptideytvids@gmail.com"

      - name: Commit updated JSON
        run: |
          git add backend/data.json
          git commit -m "Update story1.json from GitHub Action" || echo "No changes to commit"

      - name: Push changes using Fine-Grained PAT
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://$PAT_TOKEN@github.com/RiptideVideos/JustTheInfo
          git push origin main